# TOTAL NUMBER OF ORDERS PLACED.

SELECT COUNT(DISTINCT ORDER_ID)
FROM
	ORDERS_CLEAN;

# TOTAL REVENUE GENERATED FROM PIZZA SALES.
	
SELECT SUM(TOTAL_SALES) AS TOTAL_REVENUE
FROM
	(
		SELECT
			OD.PIZZA_ID,
			P.PRICE PRICE,
			SUM(QUANTITY),
			PRICE * SUM(QUANTITY) AS TOTAL_SALES
		FROM
			ORDER_DETAILS_CLEAN OD
			JOIN PIZZAS_CLEAN P ON OD.PIZZA_ID = P.PIZZA_ID
		GROUP BY
			OD.PIZZA_ID,
			P.PRICE
		ORDER BY
			OD.PIZZA_ID
	) P;

SELECT
	SUM(OD.QUANTITY * P.PRICE)
FROM
	ORDER_DETAILS_CLEAN OD
	JOIN PIZZAS_CLEAN P ON OD.PIZZA_ID = P.PIZZA_ID;

# IDENTIFYING THE HIGHEST - PRICED PIZZA.

WITH PIZZA_RANK AS (
	SELECT
		PIZZA_TYPE_ID,
		SIZE,
		PRICE,
		DENSE_RANK() OVER (
			PARTITION BY
				SIZE
			ORDER BY
				PRICE DESC
		) AS DR
	FROM
		PIZZAS_CLEAN
)
SELECT
	*
FROM
	PIZZA_RANK
WHERE
	DR = 1;

# IDENTIFYING THE MOST COMMON PIZZA SIZE ORDERED.

SELECT SIZE,
SUM(QUANTITY) ORDER_COUNT
FROM
	ORDER_DETAILS_CLEAN OD
	JOIN PIZZAS_CLEAN P ON OD.PIZZA_ID = P.PIZZA_ID
GROUP BY
	SIZE
ORDER BY
	ORDER_COUNT DESC;

# TOP 5 MOST ORDERED PIZZA TYPES ALONG WITH THEIR QUANTITIES.
	
SELECT PT.NAME,
	SUM(QUANTITY) ORDER_COUNT,
	DENSE_RANK() OVER (
		ORDER BY
			SUM(QUANTITY) DESC
	)
FROM
	ORDER_DETAILS_CLEAN OD
	JOIN PIZZAS_CLEAN P ON OD.PIZZA_ID = P.PIZZA_ID
	JOIN PIZZA_TYPES_CLEAN PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY
	P.PIZZA_TYPE_ID,
	PT.NAME;


# FINDING THE TOTAL QUANTITY OF EACH PIZZA CATEGORY ORDERED.

SELECT CATEGORY,
SUM(QUANTITY) ORDER_COUNT
FROM
	PIZZA_TYPES_CLEAN PT
	JOIN PIZZAS_CLEAN P ON PT.PIZZA_TYPE_ID = P.PIZZA_TYPE_ID
	JOIN ORDER_DETAILS_CLEAN OD ON OD.PIZZA_ID = P.PIZZA_ID
GROUP BY
	CATEGORY
ORDER BY
	ORDER_COUNT DESC;

# DETERMINING THE DISTRIBUTION OF ORDERS BY HOUR OF THE DAY.

SELECT EXTRACT(
	HOUR
	FROM
		ORDER_TIME
) AS HOUR,
COUNT(ORDER_ID),
DENSE_RANK() OVER (
	ORDER BY
		COUNT(ORDER_ID) DESC
)
FROM
	ORDERS_CLEAN
GROUP BY
	HOUR;

# THE CATEGORY - WISE DISTRIBUTION OF PIZZAS.

SELECT CATEGORY,
SUM(QUANTITY) ORDER_COUNT,
ROUND(
	100.0 * SUM(QUANTITY) / SUM(SUM(QUANTITY)) OVER (),
	2
) AS PERCENTAGE_SHARE
FROM
	PIZZA_TYPES_CLEAN PT
	JOIN PIZZAS_CLEAN P ON PT.PIZZA_TYPE_ID = P.PIZZA_TYPE_ID
	JOIN ORDER_DETAILS_CLEAN OD ON OD.PIZZA_ID = P.PIZZA_ID
GROUP BY
	CATEGORY
ORDER BY
	ORDER_COUNT DESC;

# AVERAGE NUMBER OF PIZZAS ORDERED PER DAY.

WITH DAILY_PIZZAS AS (
	SELECT
		ORDER_DATE,
		SUM(QUANTITY) DAILY_TOTAL
	FROM
		ORDERS_CLEAN
		JOIN ORDER_DETAILS_CLEAN ON ORDERS_CLEAN.ORDER_ID = ORDER_DETAILS_CLEAN.ORDER_ID
	GROUP BY
		ORDER_DATE
)
SELECT
	ROUND(AVG(DAILY_TOTAL))
FROM
	DAILY_PIZZAS;

# TOP 3 MOST ORDERED PIZZA TYPES BASED ON REVENUE.

SELECT NAME,
SUM(PRICE * QUANTITY) AS TOTAL_SALES
FROM
	ORDER_DETAILS_CLEAN OD
	JOIN PIZZAS_CLEAN P ON OD.PIZZA_ID = P.PIZZA_ID
	JOIN PIZZA_TYPES_CLEAN PT ON PT.PIZZA_TYPE_ID = P.PIZZA_TYPE_ID
GROUP BY
	PT.NAME
ORDER BY
	TOTAL_SALES DESC;

# PERCENTAGE CONTRIBUTION OF EACH PIZZA TYPE TO TOTAL REVENUE.

SELECT NAME,
SUM(PRICE * QUANTITY) AS TOTAL_SALES,
ROUND(
	SUM(PRICE * QUANTITY) * 100 / SUM(SUM(PRICE * QUANTITY)) OVER (),
	2
) AS PERCENTAGE_CONTRIBUTION
FROM
	ORDER_DETAILS_CLEAN OD
	JOIN PIZZAS_CLEAN P ON OD.PIZZA_ID = P.PIZZA_ID
	JOIN PIZZA_TYPES_CLEAN PT ON PT.PIZZA_TYPE_ID = P.PIZZA_TYPE_ID
GROUP BY
	NAME
ORDER BY
	TOTAL_SALES DESC;

# CUMULATIVE REVENUE GENERATED OVER TIME.

WITH DAILY_REVENUE AS (
	SELECT
		O.ORDER_DATE,
		SUM(OD.QUANTITY * P.PRICE) AS DAILY_REVENUE
	FROM
		ORDERS_CLEAN O
		JOIN ORDER_DETAILS_CLEAN OD ON O.ORDER_ID = OD.ORDER_ID
		JOIN PIZZAS_CLEAN P ON OD.PIZZA_ID = P.PIZZA_ID
	GROUP BY
		O.ORDER_DATE
)
SELECT
	ORDER_DATE,
	DAILY_REVENUE,
	SUM(DAILY_REVENUE) OVER (
		ORDER BY
			ORDER_DATE
	) AS CUMULATIVE_REVENUE
FROM
	DAILY_REVENUE
ORDER BY
	ORDER_DATE;

# TOP 3 MOST ORDERED PIZZA TYPES BASED ON REVENUE FOR EACH PIZZA CATEGORY.

SELECT *
FROM
	(
		SELECT
			CATEGORY,
			PT.PIZZA_TYPE_ID,
			SUM(QUANTITY) AS ORDER_COUNT,
			DENSE_RANK() OVER (
				PARTITION BY
					CATEGORY
				ORDER BY
					SUM(QUANTITY) DESC
			) AS DR
		FROM
			PIZZA_TYPES_CLEAN PT
			JOIN PIZZAS_CLEAN P ON PT.PIZZA_TYPE_ID = P.PIZZA_TYPE_ID
			JOIN ORDER_DETAILS_CLEAN OD ON OD.PIZZA_ID = P.PIZZA_ID
		GROUP BY
			CATEGORY,
			PT.PIZZA_TYPE_ID
	) RANKING
WHERE
	DR <= 3;
